/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.HashBasedTable;

public class HelloOtus {
    public static void main(String... args) {
        HashBasedTable<String, String, String> statusMap = HashBasedTable.create();
        statusMap.put("F", "Insert", "NEWT");
        statusMap.put("H", "Cancel", "CANC");

        System.out.println("Input key1:");
        String key1 = System.console().readLine();
        System.out.println("Input key2:");
        String key2 = System.console().readLine();

        System.out.format(
                "For key1 = %s and key2 = %s status is: %s", key1, key2,
                statusMap.contains(key1, key2) ? statusMap.get(key1, key2) : "Unknown"
        );
    }
}
